### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-serving-content-with-express-OctGcX#1]
@stuartpearman @erikgillespie Can you take a look at this? It's [hosted here](https://katie-kfxl35erbteu5octgcx.herokuapp.com/) and meets the following criteria:

- [x] No code is repeated in your files; create a partial for any shared elements (nav, head, header, etc.)
- [x] Make a navigation to move throughout your site, using `forEach` to create a list where each item links to the appropriate data page
- [x] Each item should have an object with an image, a link, a title, and more properties based on your topic (i.e. sandwich ingredients, movie release date, etc.)
- [x] There should be 3 data pages, and a homepage, routes should be created in Express for each.
- [x] Use data appropriately with HTML tags (paragraphs in `p` tags, headings in `h1`-`h6`, etc.)
- [x] Use `express.static` to create a folder for static assets (images, stylesheets)

Whew! The more object-dependent stuff (like passing a one object from the array into a view) took me a while. I would still like to make it a little dryer by having a layout, rather than 2 page views, but I guess it's okay. :)

See if this is what you had in mind! Forgive the ugly CSS and focus on the cute cats.

**Comment by stuartpearman** [comment]
@KatieMFritz I literally ooh'd and ah'd a few times looking through your code, very nice, better than I would have done 🙂  :shipit:
